<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TmpRegistration extends Model
{
    protected $fillable = [
        "sf_id",
        "tipo_propriedade",
        "id_regiao",
        "regiao",
        "id_projeto",
        "projeto",
        "localidade",
        "talhao",
        "nro_ciclo",
        "nro_rotacao",
        "tipo",
        "feicao_pai",
        "descricao_de_uso_do_solo",
        "fase",
        "bacia",
        "solo",
        "relevo",
        "espacamento",
        "sistema_de_propagacao",
        "mat_genetico",
        "especie",
        "data_plantio",
        "mes_de_plantio",
        "regime",
        "manejo",
        "sitio",
        "vlr_area",
        "area_gis",
        "atualizar_via_gis",
        "distancia_media_transporte_km",
        "distancia_media_baldeio",
        "situacao",
        "cd_uso_solo_pai",
        "planooperacao",
        "cd_projeto_investimento",
        "dcr_projeto_investimento",
        "cod_tarefa_proj_invest",
        "id_terra_potencial",
        "responsavel",
        "observacoes",
        "densidade_basica",
        "certificado_fsc",
        "n_notrato_bndes",
        "cr",
        "experimento",
        "nivel_subbosque",
        "projeto_microbacia",
        "grupo_de_tratamento",
        "responsavel_tecnico_plantio",
        "art_plantio",
        "identificador_pj",
        "cnpj",
        "desbaste",
        "bioma",
        "tipologia",
        "un",
        "registro",
        "ativo",
        "created_at",
        "updated_at",
    ];
}
